### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by gregoryyoung** [aumcode/nfx#1]
Are there any particular things you would like followed on contributions?

One thing I may see get some pushback in the style is the use of m_ as most people will have to reconfigure their tooling for it.

**Comment by itadapter** [comment]
We will add a detailed list of naming conventions and "quick start" guide in a few days.
There are pretty specific requirements on what can be used due to the fact that albeit being a C# code this is not a typical bloated MS .NET solution so special care should be taken not to use/reference "fat /external classes"

**Comment by itadapter** [comment]
Added CONTRIBUTING guide for naming conventions and rules to trunk
